### ISSUE TITLE
Problem with folding region

### ISSUE THREAD

**Issue by ryuukk** [Pure-D/serve-d#309]
Let's take this code:

```D
    struct Data
    {
        int a;
    private: // <-- this messes up fold region
        int b;
    }
```

If you try to fold ``struct Data``

Then it stops at ``private:``

![image](https://user-images.githubusercontent.com/44361234/226211100-b8013385-e94e-411c-8538-c096ec55203d.png)

![image](https://user-images.githubusercontent.com/44361234/226211112-ae40b36f-612c-420e-b1af-8d1dde24ec54.png)

Expected:

It should fold the struct like this:

![image](https://user-images.githubusercontent.com/44361234/226211121-01e0277a-bb40-420e-84a2-bd4b6480245b.png)

On super long code 

Note:

It works fine if ``private:`` is indented more than the ``struct Data``

![image](https://user-images.githubusercontent.com/44361234/226211182-efd8ea4d-b9c2-461e-9593-0c6c21fab9f7.png)

![image](https://user-images.githubusercontent.com/44361234/226211194-e8816641-0fbf-4dcb-8098-fd5d4c1068a7.png)

It's probably a vscode issue, but i'm not sure

**Comment by WebFreak001** [comment]
it seems you are on stable, where folding regions weren't implemented yet. Try again with serve-d nightly/beta

**Comment by WebFreak001** [comment]
hm then the folding provider seems to be completely broken in that code, since the folding region indicator should be on the line with `struct Data`

can you share code to reproduce? This is how a simple struct reproduces here with master serve-d:

![image](https://user-images.githubusercontent.com/2035977/226230260-adcfaf17-7224-4496-8eb0-a37eb76dce1a.png)

![image](https://user-images.githubusercontent.com/2035977/226230283-48fc256b-7f36-4e47-93f2-527cb9c2ba8c.png)

![image](https://user-images.githubusercontent.com/2035977/226230318-1fe55f6b-7141-446c-a785-a11c45d3a3eb.png)

![image](https://user-images.githubusercontent.com/2035977/226230331-e0243455-6b67-4c0e-834c-683b8261f18d.png)

**Comment by WebFreak001** [comment]
you are right, it's broken in the pre-compiled releases, might be an issue with selections / dependencies. I'll investigate.

**Comment by WebFreak001** [comment]
I talked with Geod24 about this, the problem here is that libdparse behaves like a 1.x.y library with breaking changes decisions, but isn't released like one. Making libdparse 1.0.0 is gonna improve things here and also give users a guarantee that breaking changes will have a migration process and only break in a new major.

**Comment by WebFreak001** [comment]
@ryuukk I had it reproduced and have been trying around what could be broken here, but it turned out I just accidentally downloaded stable instead of nightly. On pre-built nightly it actually works fine for me.

Can you check in the trace: verbose code-d/serve-d output log if it contains `foldingRangeProvider` anywhere? If that's in there, the folding should work.

It looks like the only way in code how folding could break is if the dcdext component wasn't loaded, but dcdext does not have any dependencies and should always succeed, unless it doesn't have any workspace / folder instance.

**Comment by WebFreak001** [comment]
ah can reproduce it if I don't open any folder/workspace with vscode. Will fix

**Comment by WebFreak001** [comment]
the problem has been solved on master
