### ISSUE TITLE
Blocked on Anti-virus solutions.

### ISSUE THREAD

**Issue by ZHANITEST** [Pure-D/serve-d#87]
Title is description.. 

* Target: https://github.com/Pure-D/serve-d/releases/tag/v0.6.0
* VirusTotal : https://www.virustotal.com/gui/file/da11cfc9a0618bfb95bdc012cd9b890116d3f65f727a64bed8d7d332460a8524/detection

I don't believe that. But I think need to check a reason.
Thanks.

**Comment by WebFreak001** [comment]
the deploy log for that build can be found here: https://github.com/Pure-D/serve-d/runs/351002156

Because the nightly releases (https://github.com/Pure-D/serve-d/releases/tag/nightly) are also reported like the latest release, I believe it's simply a false positive in the virus detection.

It might be related that there is download code to download the precompiled DCD .exe from github and run it immediately.

**Comment by ZHANITEST** [comment]
Hi @WebFreak001.
I'm use Bitdefender series(IS, Free) now. Free version even blocking it when I try to download on ZIP file...

<img width="614" alt="2020-01-24 17_27_29-" src="https://user-images.githubusercontent.com/6543940/73054985-12a24c00-3ecf-11ea-8b79-f2b92f1f9d3e.png">

I think so too that is a mistake of bitdefender engine.
But some peoples will be surprised who try to install *code-d* plugin on *VS Code*.
I don't know how long for fix this problem on AV solutions..

Thanks.

**Comment by andre2007** [comment]
Also `McAfee Endpoint Security` reports serve-d now as trojaner `ATP/Suspect!3863ec8b69eb`.

**Comment by andre2007** [comment]
As workaround: You can install the plugin `Remote - WSL` from Microsoft to run your actual coding / plugins like `serve-d` within a WSL distribution like Ubuntu. This works pretty fantastic as long as you develop a server / cmd tool and not a GUI of course.

**Comment by helikopterodaktyl** [comment]
As of today, Windows Defender is pestering me about "Trojan:Win32/Wacatac.D!ml" in serve-d.

**Comment by ZHANITEST** [comment]
All right. I re-build it and didn't detect any AV solutions.

# DUB options
* --compiler: ldc2, LDC - the LLVM D compiler (1.23.0)
* --arch: x86_64

# VirusTotal
* [94bb9ab184d7252f498232160d571b7bb64769bbc71aa70a80c91da876e6517b](https://www.virustotal.com/gui/file/94bb9ab184d7252f498232160d571b7bb64769bbc71aa70a80c91da876e6517b/detection)

# Binary
* On my OneDrive: https://1drv.ms/u/s!AmL69da7qLEak1Ep7UbJ9IB_4FH4?e=QS6yfV

Thanks.

**Comment by ZHANITEST** [comment]
@andre2007 

Good idea. But can not solve this problem.
Some dlang projects got same situation like `dub` or `ldc2`.

**Comment by WebFreak001** [comment]
@ZHANITEST I don't think your binary would be malicious, however I don't want people sharing their own compiled binaries publicly on this GitHub page (as I can't really verify them and I would be blamed if there is anything wrong)

However it is good to know that possibly the blocked binary would be fixed by a new compilation using a newer LDC version. For people who want to get such a binary they can compile it using your provided instructions, I will plan on releasing a new pre-release soon so there is a new compiled executable.

**Comment by ZHANITEST** [comment]
Thanks for reply me @WebFreak001 

`I would be blamed if there is anything wrong`
I agreed.

So, I remove my OneDrive link that shared and clone and release it my repo:
* https://github.com/ZHANITEST/serve-d-clone/releases/tag/v0.6.0

Thanks.
